-- drop table product;
CREATE TABLE product (
    barcode   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item      VARCHAR2(100),
    category  VARCHAR2(200),
    price     NUMBER,
    discount  NUMBER,
    available VARCHAR2(1)
);
COMMIT;